name: Swift

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04]

    runs-on: ${{matrix.os}}

    steps:
    - name: Install Swift
      if: matrix.os == 'ubuntu-20.04'
      uses: sersoft-gmbh/SwiftyActions@v1
      with:
          release-version: 5.3.2
          platform: ${{matrix.os}}
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
          path: .build
          key: ${{runner.os}}-${{github.repository}}-spm-${{hashFiles('**/Package.resolved')}}
          restore-keys: |
            ${{runner.os}}-${{github.repository}}-spm-
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test --enable-code-coverage
    - name: Post Codecov report
      if: matrix.os == 'macos-latest'
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
